language: python
env:
  - DJANGO_VERSION=https://github.com/django/django/archive/stable/1.4.x.zip
  - DJANGO_VERSION=https://github.com/django/django/archive/stable/1.5.x.zip
  - DJANGO_VERSION=https://github.com/django/django/archive/stable/1.6.x.zip
python:
  - "2.6"
  - "2.7"
  - "3.3"
matrix:
  exclude:
     - python: "3.3"
       env: DJANGO_VERSION=https://github.com/django/django/archive/stable/1.4.x.zip
install:
  - pip install $DJANGO_VERSION --use-mirrors
  - pip install -e git://github.com/stephenmcd/mezzanine.git#egg=mezzanine
  - pip install . --allow-unverified pyPdf
script:
  - python setup.py test
notifications:
  irc: "irc.freenode.org#mezzanine"
  on_success: change
  on_failure: change
